### ISSUE TITLE
Docker image availability?

### ISSUE THREAD

**Issue by jackfirth** [dbohdan/automatic-api#10]
Some of these tools (like PostgREST, which is the one I'm most familiar with) provide Docker images, meaning I can use them in a Docker Compose project with no code and very little configuration. It would be helpful for me if this list said which projects have docker images maintained by the project authors.

**Comment by dbohdan** [comment]
I don't want to add another column to the table (the columns are narrow enough as they are), but I could put this information in the notes. (E.g., the notes could simply say "Official Docker image.") Is anyone else interested in this feature?

**Comment by dbohdan** [comment]
Done in 16ee5a640134b58c376ffffb90a94d6345895260, 107e8953e96625ca8ed0b6cfe31a34859708e64a.

**Comment by jackfirth** [comment]
Thank you, this is great!
