### ISSUE TITLE
Add loopback.io

### ISSUE THREAD

**Issue by SpeedoPasanen** [dbohdan/automatic-api#16]
The list is missing my personal favourite os nodejs framework: http://loopback.io

Rest, works with practically any db via pluggable connectors, easy auth&acl, awesome cli tool, open api spec, etc.

I'm traveling without my laptop so just an issue for now sorry. Unless someone beats me to it, i might post a PR later :)

**Comment by dbohdan** [comment]
Thanks for the suggestion, but this is not quite what I am looking to add to the list. See [CONTRIBUTING](https://github.com/dbohdan/automatic-api/blob/master/CONTRIBUTING.md#what-projects-to-submit) for why.
