### ISSUE TITLE
Awesome List

### ISSUE THREAD

**Issue by styfle** [dbohdan/automatic-api#3]
Consider turning this into an [Awesome List](https://github.com/sindresorhus/awesome) because everyone likes cool sunglasses 😎 

See an example: https://github.com/styfle/awesome-online-ide

**Comment by dbohdan** [comment]
My list has a different format from what is recommended for an awesome list<sup>1</sup>, so it may not fit on there. I've just asked if it would. (The different format is deliberate to help the reader compare between many similar options.)

1. It is secretly a table.

**Comment by dbohdan** [comment]
The answer is no. I got the clarification that generated lists are not eligible.

**Comment by styfle** [comment]
I see. I didn't realize this list was generated.

**Comment by dbohdan** [comment]
It is. The actual data resides in `data/*.yml`; `render-template.go` reads the data, fetches the repository stats from GitHub, generates the table, and puts it in `README.md.template` to create `README.md`.
