### ISSUE TITLE
Add Apinizer to the list 

### ISSUE THREAD

**Issue by mustafahalil** [dbohdan/automatic-api#32]
Hi, please add Apinizer to the list, thanks.

<tr>
    <td><a href="https://www.apinizer.com/products/api-creator/">Apinizer</a></td>
    <td>Oracle, MySQL, PostgreSQL, MsSQL, IBM DB2, SAP Sybase ASE, Apache Impala, Apache Hive </td>
    <td>REST</td>
    <td>Java</td>
    <td>Proprietary</td>
    <td>n/a</td>
    <td>Supports SQL operations and Procedure Call, creates Swagger & OpenAPI automatically <a href="https://www.youtube.com/watch?v=5723z0TuB2U&feature=youtu.be">Preview</a>.</td>
  </tr>

**Comment by dbohdan** [comment]
Hello!  I can't find pricing information on your site.  Is it public?  Per the rules,

> Self-hosted open source and proprietary software is allowed on this list, as well as software as a service (SaaS) if it works with an existing database. (E.g., a SaaS REST API that connects to the user's PostgreSQL server can be on the list, but Amazon DynamoDB can't.) Proprietary software and SaaS that is out of beta must have its pricing publicly available. Enterprise "call us" pricing is not allowed.

**Comment by mustafahalil** [comment]
It has pricing list but we are renewing our pricing modals, so it is closed for  a while, I can apply later when it is available

**Comment by dbohdan** [comment]
Okay, I'll put this issue on hold without closing it.  Comment when the pricing is available.

**Comment by mustafahalil** [comment]
Hi, we published pricing list on https://www.apinizer.com/pricing/
