### ISSUE TITLE
make fails: GitHub API: Bad credentials

### ISSUE THREAD

**Issue by frafra** [dbohdan/automatic-api#33]
```make
go fmt render-template.go
go: downloading github.com/magiconair/properties v1.8.5
go: downloading github.com/rhinoman/go-commonmark v0.0.0-20170821135903-b6e895a10b08
go run render-template.go > README.md
2021/08/31 10:49:49 GitHub API: Bad credentials
exit status 1
make: *** [Makefile:13: README.md] Error 1
```

**Comment by dbohdan** [comment]
`render-template.go` needs a GitHub access token in the environment variable `GITHUB_TOKEN`.

(I don't expect contributors to run it.  If you want to propose changes to this repository, make a PR changing the data, and I will rerender the readme myself after I merge it.)
