### ISSUE TITLE
Few missing items

### ISSUE THREAD

**Issue by amal-chandran** [dbohdan/automatic-api#42]
- https://graphjin.com/
- https://www.graphile.org/postgraphile/realtime/
- https://supabase.com/
- https://aws.amazon.com/appsync/

**Comment by dbohdan** [comment]
Note: PostGraphile is on the list. I think AppSync doesn't qualify. It seems to be a SaaS you can't connect to your own DB. Supabase qualifies. Does GraphJin require you to maintain a schema in the form of a GraphQL query? It looks like it.

**Comment by ebrahimghane** [comment]
hi
i recommend to add Graphql Mesh to list
https://github.com/Urigo/graphql-mesh

**Comment by kdhrubo** [comment]
Hi Please add - db2rest - https://github.com/kdhrubo/db2rest

**Comment by dbohdan** [comment]
Okay, this is done. Supabase and DB2Rest have been added. There is now a separate issue for GraphJin. I'll be adding GraphQL Mesh shortly. AppSync doesn't seem to qualify.

(If you want to suggest an item, please don't comment here. Open a new issue.)
